### ISSUE TITLE
Turn off Pop!_Shop opening on first boot.

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/iso#152]

**Comment by jackpot51** [comment]
Can more information be provided?

**Comment by sarahpandabeara** [comment]
Carl and I had it happen to us twice this morning when testing install that upon first login, Pop!_Shop opened (unprompted). Once while trying to open Firefox and another time on a different machine when not trying to open anything (I think).

**Comment by sarahpandabeara** [comment]
I'd like to confirm that Ben can duplicate it with Carl's help.

**Comment by brs17** [comment]
I have been able to duplicate it. Working on understanding what is causing it. Will report back when more information is available.

**Comment by brs17** [comment]
Reporter info

 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
This bug happens on a system where updates are available. When logging into a system, if a search for a program is done, and selected prior to the notification of the update appearing, then the Pop!_Shop opens up.

**Steps to reproduce (if you know)**
A program must be searched for.
The program must either be selected by hitting enter or clicked on in the search results.

![screenshot from 2017-10-12 16-44-28](https://user-images.githubusercontent.com/7460774/31522855-4b80de0e-af6d-11e7-9b27-b518e69367d6.png)

**Expected behaviour**
Only the program selected should open.

**Comment by isantop** [comment]
This issue was moved to pop-os/shop#25
