### ISSUE TITLE
A2DP For Bluetooth Devices when on Ubuntu 17.10 Base

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#59]
```
 * Distribution - (run ```lsb_release -a```)
Pop!_OS 17.04
```

**Issue/Bug Description**
A2DP needs testing when Pop!_OS is rebased on 17.10. 

From Ubuntu weekly newsletter
[1] We’ve landed some important fixes to audio in Artful this week, and users
of Bluetooth and USB speakers should seen a significant improvement in
usability - for example switching to the device automatically on connection
and preferring the high quality A2DP Bluetooth profile over the low quality
HSP/HFP one.  There is an important caveat/bug though, because of the way
GDM and PulseAudio interact, you can’t use a Bluetooth audio-device with a
screen-reader at the greeter.  Once you’re logged in though, everything
should work again, and for users who don’t need use a screen-reader, the
A2DP profile is now available for use once you’re logged in.  We’re working
on a proper fix for this with upstreams.  If you’re using a screen-reader
at the greeter I’d like to hear from you.

[1] https://lists.ubuntu.com/archives/ubuntu-desktop/2017-July/005052.html

**Comment by WatchMkr** [comment]
Also check sync with youtube. From Pop!_Chat:

"wow, such lag with youtube+a2dp... everything out of sync... turn off bluetooth and full sync... "

**Comment by brs17** [comment]
So far, struggling to recreate this issue. Experienced what we thought was a bug while watching a video that was buffering and struggling to play. While this was happening the video and audio were not synced. Otherwise the video and audio(playing on Bluetooth speaker) have played well without any noticeable sync issues.

Will continue to work on recreating this bug. Also going to try and test on different Bluetooth devices.

**Comment by brs17** [comment]
We have been unable to reproduce this issue on our(System76) hardware. A2DP Bluetooth devices are recognized and by default set in the A2DP Profile. If problems persist feel free to reopen the bug with detailed steps to reproduce the bug.
